export const data =[
    {
      image: "https://images.meesho.com/images/products/71498820/49krb_512.jpg",
      name: "Attractive Bags % Footwear",
       mkt: "Sold By: CRAFTOS HANDICRAFTS",
      price: "₹1343",
      aprice: "₹1747",
      discount: "23.1% off",
      firstorder: "₹144 discount on 1st order",
      rating: "1133 Reviews",
      rating2: 2.4
    },
    {
      image: "https://images.meesho.com/images/products/65407412/xlnei_512.jpg",
      name: "Kurtas Stitched Suits",
      mkt: "Sold By: The Strange",
      price: "₹1451",
      aprice: "₹1765",
      discount: "17.8% off",
      firstorder: "₹132 discount on 1st order",
      rating: "845 Reviews",
      rating2: 4.8
    },
    {
      image: "https://images.meesho.com/images/products/10419631/ounxq_512.jpg",
      name: "Beauty & Health Products",
      mkt: "Sold By: DistinctTrends",
      price: "₹473",
      aprice: "₹1730",
      discount: "72.7% off",
      firstorder: "₹136 discount on 1st order",
      rating: "1053 Reviews",
      rating2: 2
    },
    {
      image: "https://images.meesho.com/images/products/84550725/jpvso_512.jpg",
      name: "Alluring Kurtis",
      mkt: "Sold By: Clean Clothe",
      price: "₹746",
      aprice: "₹1739",
      discount: "57.1% off",
      firstorder: "₹12 discount on 1st order",
      rating: "609 Reviews",
      rating2: 2.5
    },
    {
      image: "https://images.meesho.com/images/products/62447710/vdtem_512.jpg",
      name: "Voguish Bedsheets",
      mkt: "Sold By: Clean Clothe",
      price: "₹732",
      aprice: "₹1723",
      discount: "57.5% off",
      firstorder: "₹27 discount on 1st order",
      rating: "1439 Reviews",
      rating2: 4.9
    },
    {
      image: "https://images.meesho.com/images/products/80415378/71lqb_512.jpg",
      name: "Fancy Mobile Holders",
      mkt: "Sold By: Retro Walk",
      price: "₹854",
      aprice: "₹1731",
      discount: "50.7% off",
      firstorder: "₹20 discount on 1st order",
      rating: "1179 Reviews",
      rating2: 3.6
    },
    {
      image: "https://images.meesho.com/images/products/92027352/gwcrc_512.jpg",
      name: "Attractive Bags % Footwear",
      mkt: "Sold By: Zalya",
      price: "₹1362",
      aprice: "₹1787",
      discount: "23.8% off",
      firstorder: "₹125 discount on 1st order",
      rating: "671 Reviews",
      rating2: 4.3
    },
    {
      image: "https://images.meesho.com/images/products/45660991/xfiwl_512.jpg",
      name: "Aagyeyi Sensational Women",
      mkt: "Sold By: Shershaan",
      price: "₹996",
      aprice: "₹1729",
      discount: "42.4% off",
      firstorder: "₹46 discount on 1st order",
      rating: "754 Reviews",
      rating2: 3.4
    },
    {
      image: "https://images.meesho.com/images/products/69763861/7wmjv_512.jpg",
      name: "Columbus Sports Trendy Shoe",
      mkt: "Sold By: The Coarse",
      price: "₹1087",
      aprice: "₹1779",
      discount: "38.9% off",
      firstorder: "₹34 discount on 1st order",
      rating: "154 Reviews",
      rating2: 4.9
    },
    {
      image: "https://images.meesho.com/images/products/67240284/pzgug_512.jpg",
      name: "Women Adelyn Feminine",
      mkt: "Sold By: Zalya",
      price: "₹1560",
      aprice: "₹1744",
      discount: "10.6% off",
      firstorder: "₹99 discount on 1st order",
      rating: "1621 Reviews",
      rating2: 3.8
    },
    {
      image: "https://images.meesho.com/images/products/72817099/r3dtt_512.jpg",
      name: "Trendy Poly Cotton",
      mkt: "Sold By: The Day Garb",
      price: "₹1282",
      aprice: "₹1751",
      discount: "26.8% off",
      firstorder: "₹33 discount on 1st order",
      rating: "1628 Reviews",
      rating2: 3.8
    },
    {
      image: "https://images.meesho.com/images/products/78212933/nvqza_512.jpg",
      name: "Classy Facepack & Scrubs",
      mkt: "Sold By: Fashioned Fashion",
      price: "₹1469",
      aprice: "₹1771",
      discount: "17.1% off",
      firstorder: "₹69 discount on 1st order",
      rating: "1390 Reviews",
      rating2: 2.5
    },
    {
      image: "https://images.meesho.com/images/products/49935886/fhyup_512.jpg",
      name: "Alsiha Salwars",
      mkt: "Sold By: V King Kohli",
      price: "₹1436",
      aprice: "₹1786",
      discount: "19.6% off",
      firstorder: "₹95 discount on 1st order",
      rating: "1485 Reviews",
      rating2: 1.9
    },
    {
      image: "https://images.meesho.com/images/products/45636641/nsprg_512.jpg",
      name: "Retro Fabric Feminine",
      mkt: "Sold By: Enough Apparel",
      price: "₹956",
      aprice: "₹1708",
      discount: "44.0% off",
      firstorder: "₹75 discount on 1st order",
      rating: "864 Reviews",
      rating2: 1.9
    },
    {
      image: "https://images.meesho.com/images/products/55080609/v0xms_512.jpg",
      name: "Unique Fashion Wallets",
      mkt: "Sold By: The Day Garb",
      price: "₹1051",
      aprice: "₹1778",
      discount: "40.9% off",
      firstorder: "₹108 discount on 1st order",
      rating: "75 Reviews",
      rating2: 3.6
    },
    {
      image: "https://images.meesho.com/images/products/97453482/q8zip_512.jpg",
      name: "Trendy Refined Sarees",
      mkt: "Sold By: BRAND PLUS TRADING",
      price: "₹703",
      aprice: "₹1729",
      discount: "59.3% off",
      firstorder: "₹81 discount on 1st order",
      rating: "22 Reviews",
      rating2: 2.4
    },
    {
      image: "https://images.meesho.com/images/products/24652731/4b7cf_512.jpg",
      name: "Polyester Double Toys",
      mkt: "Sold By: Clean Clothe",
      price: "₹1362",
      aprice: "₹1702",
      discount: "20.0% off",
      firstorder: "₹131 discount on 1st order",
      rating: "1431 Reviews",
      rating2: 4.1
    },
    {
      image: "https://images.meesho.com/images/products/29664520/c108b_512.jpg",
      name: "Jivika Women",
      mkt: "Sold By: BHARTI TRADING CO.",
      price: "₹1663",
      aprice: "₹1764",
      discount: "5.7% off",
      firstorder: "₹61 discount on 1st order",
      rating: "738 Reviews",
      rating2: 3.9
    },
    {
      image: "https://images.meesho.com/images/products/57720236/iasim_512.jpg",
      name: "Alite Bejeweled Rings",
      mkt: "Sold By: SHUBHARAMBH VENTURES",
      price: "₹669",
      aprice: "₹1733",
      discount: "61.4% off",
      firstorder: "₹8 discount on 1st order",
      rating: "137 Reviews",
      rating2: 1.9
    },
    {
      image: "https://images.meesho.com/images/products/41531653/mujbo_512.jpg",
      name: "Black Goggles",
      mkt: "Sold By: Bewitched Boutique",
      price: "₹756",
      aprice: "₹1786",
      discount: "57.7% off",
      firstorder: "₹11 discount on 1st order",
      rating: "1370 Reviews",
      rating2: 1.5
    },
    {
      image: "https://images.meesho.com/images/products/80160071/rxlbf_512.jpg",
      name: "Aishani Fashion Kurtis",
      mkt: "Sold By: The Best",
      price: "₹1221",
      aprice: "₹1789",
      discount: "31.7% off",
      firstorder: "₹62 discount on 1st order",
      rating: "1208 Reviews",
      rating2: 2.5
    },
    {
      image: "https://images.meesho.com/images/products/66385501/ukyer_512.jpg",
      name: "Kurti Fabrics",
      mkt: "Sold By: happy creation sarees",
      price: "₹1457",
      aprice: "₹1714",
      discount: "15.0% off",
      firstorder: "₹128 discount on 1st order",
      rating: "1618 Reviews",
      rating2: 4.4
    },
    {
      image: "https://images.meesho.com/images/products/50692904/bvjju_512.jpg",
      name: "Stylish Agile Glass",
      mkt: "Sold By: Magnificent check",
      price: "₹1612",
      aprice: "₹1767",
      discount: "8.8% off",
      firstorder: "₹44 discount on 1st order",
      rating: "628 Reviews",
      rating2: 4.2
    },
    {
      image: "https://images.meesho.com/images/products/24048385/42044_512.jpg",
      name: "Ravishing Furnitures",
      mkt: "Sold By: Fashionista",
      price: "₹750",
      aprice: "₹1692",
      discount: "55.7% off",
      firstorder: "₹137 discount on 1st order",
      rating: "447 Reviews",
      rating2: 4.6
    },
    {
      image: "https://images.meesho.com/images/products/11984978/e8ea4_512.jpg",
      name: "Lehenga Superior",
      mkt: "Sold By: HandClothing",
      price: "₹705",
      aprice: "₹1776",
      discount: "60.3% off",
      firstorder: "₹95 discount on 1st order",
      rating: "248 Reviews",
      rating2: 3
    },
    {
      image: "https://images.meesho.com/images/products/16434105/78bfe_512.jpg",
      name: "Trendy Poly Cotton",
      mkt: "Sold By: The Observed check",
      price: "₹1318",
      aprice: "₹1742",
      discount: "24.3% off",
      firstorder: "₹124 discount on 1st order",
      rating: "1548 Reviews",
      rating2: 1.8
    },
    {
      image: "https://images.meesho.com/images/products/44401618/ablpe_512.jpg",
      name: "Trendy Superior Suits",
      mkt: "Sold By: Term Temporal",
      price: "₹1683",
      aprice: "₹1780",
      discount: "5.4% off",
      firstorder: "₹14 discount on 1st order",
      rating: "151 Reviews",
      rating2: 2.3
    },
    {
      image: "https://images.meesho.com/images/products/41713416/fef4b_512.jpg",
      name: "Trendy Pretty Kurtis",
      mkt: "Sold By: NDS CREATION",
      price: "₹410",
      aprice: "₹460",
      discount: "10.9% off",
      firstorder: "₹66 discount on 1st order",
      rating: "69 Reviews",
      rating2: 4
    },
    {
      image: "https://images.meesho.com/images/products/74099480/ndoba_512.jpg",
      name: "Alite Bejeweled Rings",
      mkt: "Sold By: Fashioned Fashion",
      price: "₹1097",
      aprice: "₹1706",
      discount: "35.7% off",
      firstorder: "₹8 discount on 1st order",
      rating: "443 Reviews",
      rating2: 3.3
    },
    {
      image: "https://images.meesho.com/images/products/69640167/olei1_512.jpg",
      name: "Fancy Men Trousers",
      mkt: "Sold By: Manner Pro",
      price: "₹1563",
      aprice: "₹1770",
      discount: "11.7% off",
      firstorder: "₹74 discount on 1st order",
      rating: "1476 Reviews",
      rating2: 2.5
    },
    {
      image: "https://images.meesho.com/images/products/23920358/698f8_512.jpg",
      name: "Voguish Attractive Wears",
      mkt: "Sold By: Mangalsutras",
      price: "₹716",
      aprice: "₹1704",
      discount: "58.0% off",
      firstorder: "₹60 discount on 1st order",
      rating: "444 Reviews",
      rating2: 3.7
    },
    {
      image: "https://images.meesho.com/images/products/79977062/y9uvs_512.jpg",
      name: "Usha Iron",
      mkt: "Sold By: Finest Stitch",
      price: "₹1654",
      aprice: "₹1721",
      discount: "3.9% off",
      firstorder: "₹135 discount on 1st order",
      rating: "115 Reviews",
      rating2: 5
    },
    {
      image: "https://images.meesho.com/images/products/22264347/5f177_512.jpg",
      name: "half Ethnic Feminine",
      mkt: "Sold By: Overall",
      price: "₹1677",
      aprice: "₹1768",
      discount: "5.1% off",
      firstorder: "₹119 discount on 1st order",
      rating: "554 Reviews",
      rating2: 4.9
    },
    {
      image: "https://images.meesho.com/images/products/71036502/lwzb7_512.jpg",
      name: "New COllection Fashpack",
      mkt: "Sold By: NEW INDIA ENTERPRISES",
      price: "₹1295",
      aprice: "₹1708",
      discount: "24.2% off",
      firstorder: "₹80 discount on 1st order",
      rating: "254 Reviews",
      rating2: 4.3
    },
    {
      image: "https://images.meesho.com/images/products/6319629/f4b47_512.jpg",
      name: "Superior Quality Nail Care",
      mkt: "Sold By: National Cut",
      price: "₹1398",
      aprice: "₹1743",
      discount: "19.8% off",
      firstorder: "₹54 discount on 1st order",
      rating: "725 Reviews",
      rating2: 3.4
    },
    {
      image: "https://images.meesho.com/images/products/30839757/fqcds_512.jpg",
      name: "Salwar Suits Petite",
      mkt: "Sold By: BRAND PLUS TRADING",
      price: "₹515",
      aprice: "₹1778",
      discount: "71.0% off",
      firstorder: "₹37 discount on 1st order",
      rating: "936 Reviews",
      rating2: 2.5
    },
    {
      image: "https://images.meesho.com/images/products/917643/1_512.jpg",
      name: "Trendy Poly Cotton",
      mkt: "Sold By: Satyasaidata",
      price: "₹615",
      aprice: "₹1699",
      discount: "63.8% off",
      firstorder: "₹77 discount on 1st order",
      rating: "671 Reviews",
      rating2: 1.8
    },
    {
      image: "https://images.meesho.com/images/products/97434427/qmvnb_512.jpg",
      name: "Charvi Voguish Sarees",
      mkt: "Sold By: Zalya",
      price: "₹1688",
      aprice: "₹1698",
      discount: "0.6% off",
      firstorder: "₹24 discount on 1st order",
      rating: "1033 Reviews",
      rating2: 3.7
    },
    {
      image: "https://images.meesho.com/images/products/78056277/nie78_512.jpg",
      name: "Unique Attractive Deo",
      mkt: "Sold By: The Contemporary",
      price: "₹1426",
      aprice: "₹1766",
      discount: "19.3% off",
      firstorder: "₹4 discount on 1st order",
      rating: "922 Reviews",
      rating2: 4
    },
    {
      image: "https://images.meesho.com/images/products/34035307/txla4_512.jpg",
      name: "Cotton Suits",
      mkt: "Sold By: Mangalsutras",
      price: "₹759",
      aprice: "₹1769",
      discount: "57.1% off",
      firstorder: "₹97 discount on 1st order",
      rating: "808 Reviews",
      rating2: 3.8
    },
    {
      image: "https://images.meesho.com/images/products/27071947/b8d87_512.jpg",
      name: "Modern Half Dresses",
      mkt: "Sold By: BHARTI TRADING CO.",
      price: "₹1244",
      aprice: "₹1751",
      discount: "29.0% off",
      firstorder: "₹30 discount on 1st order",
      rating: "1194 Reviews",
      rating2: 2
    },
    {
      image: "https://images.meesho.com/images/products/67517999/zwwzb_512.jpg",
      name: "Pendrives",
      mkt: "Sold By: Clean Clothe",
      price: "₹1112",
      aprice: "₹1789",
      discount: "37.8% off",
      firstorder: "₹142 discount on 1st order",
      rating: "45 Reviews",
      rating2: 3.4
    },
    {
      image: "https://images.meesho.com/images/products/97418391/u0rew_512.jpg",
      name: "Chrvi Refined",
      mkt: "Sold By: The Coarse",
      price: "₹1395",
      aprice: "₹1747",
      discount: "20.1% off",
      firstorder: "₹129 discount on 1st order",
      rating: "217 Reviews",
      rating2: 2.2
    },
    {
      image: "https://images.meesho.com/images/products/67535883/rlw1p_512.jpg",
      name: "Trendy Pretty Suit",
      mkt: "Sold By: Vansh Enterprises",
      price: "₹791",
      aprice: "₹1736",
      discount: "54.4% off",
      firstorder: "₹140 discount on 1st order",
      rating: "647 Reviews",
      rating2: 1.7
    },
    {
      image: "https://images.meesho.com/images/products/54579361/uxmhb_512.jpg",
      name: "Semi-Stitched Suits Salwars",
      mkt: "Sold By: HandClothing",
      price: "₹544",
      aprice: "₹1707",
      discount: "68.1% off",
      firstorder: "₹118 discount on 1st order",
      rating: "1623 Reviews",
      rating2: 4.2
    },
    {
      image: "https://images.meesho.com/images/products/62465648/qbvva_512.jpg",
      name: "Designer Trendy Stylish",
      mkt: "Sold By: HandClothing",
      price: "₹997",
      aprice: "₹1720",
      discount: "42.0% off",
      firstorder: "₹137 discount on 1st order",
      rating: "922 Reviews",
      rating2: 2.8
    },
    {
      image: "https://images.meesho.com/images/products/61871013/ohwdj_512.jpg",
      name: "Twinkling Earrings",
      mkt: "Sold By: Civilian Costume",
      price: "₹1573",
      aprice: "₹1696",
      discount: "7.3% off",
      firstorder: "₹41 discount on 1st order",
      rating: "539 Reviews",
      rating2: 1.6
    },
    {
      image: "https://images.meesho.com/images/products/31295201/17c35_512.jpg",
      name: "Classic Table Lamp",
      mkt: "Sold By: GOOD PRICE STORE",
      price: "₹626",
      aprice: "₹1784",
      discount: "64.9% off",
      firstorder: "₹15 discount on 1st order",
      rating: "367 Reviews",
      rating2: 1.8
    },
    {
      image: "https://images.meesho.com/images/products/63130002/4ume5_512.jpg",
      name: "New Kids Fashions",
      mkt: "Sold By: VISENAFAB",
      price: "₹683",
      aprice: "₹1755",
      discount: "61.1% off",
      firstorder: "₹99 discount on 1st order",
      rating: "43 Reviews",
      rating2: 4.6
    },
    {
      image: "https://images.meesho.com/images/products/49408011/n4mls_512.jpg",
      name: "Superior Stylish Kajal",
      mkt: "Sold By: VISENAFAB",
      price: "₹1407",
      aprice: "₹1731",
      discount: "18.7% off",
      firstorder: "₹52 discount on 1st order",
      rating: "594 Reviews",
      rating2: 4.5
    },
    {
      image: "https://images.meesho.com/images/products/45570785/pte1n_512.jpg",
      name: "Classic Earrings",
      mkt: "Sold By: Dwell check",
      price: "₹913",
      aprice: "₹1788",
      discount: "48.9% off",
      firstorder: "₹63 discount on 1st order",
      rating: "47 Reviews",
      rating2: 2.4
    },
    {
      image: "https://images.meesho.com/images/products/62494759/zhckl_512.jpg",
      name: "Beauty & Health Products",
      mkt: "Sold By: Enough Apparel",
      price: "₹1388",
      aprice: "₹1775",
      discount: "21.8% off",
      firstorder: "₹26 discount on 1st order",
      rating: "426 Reviews",
      rating2: 2.1
    },
    {
      image: "https://images.meesho.com/images/products/63915652/9xghj_512.jpg",
      name: "Designer Trendy Stylish",
      mkt: "Sold By: Aromatic",
      price: "₹1122",
      aprice: "₹1743",
      discount: "35.6% off",
      firstorder: "₹98 discount on 1st order",
      rating: "1423 Reviews",
      rating2: 3.3
    },
    {
      image: "https://images.meesho.com/images/products/18554069/de0a4_512.jpg",
      name: "Polyester Double Toys",
      mkt: "Sold By: Rudu fashion",
      price: "₹745",
      aprice: "₹1752",
      discount: "57.5% off",
      firstorder: "₹42 discount on 1st order",
      rating: "1359 Reviews",
      rating2: 3.9
    },
    {
      image: "https://images.meesho.com/images/products/59153559/jlcis_512.jpg",
      name: "Morden Beautiful Causals",
      mkt: "Sold By: CRAFTOS HANDICRAFTS",
      price: "₹1019",
      aprice: "₹1750",
      discount: "41.8% off",
      firstorder: "₹43 discount on 1st order",
      rating: "453 Reviews",
      rating2: 1.6
    },
    {
      image: "https://images.meesho.com/images/products/61142371/khrp5_512.jpg",
      name: "Unique Attractive Deo",
      mkt: "Sold By: Studio 51 Clothing Co",
      price: "₹1037",
      aprice: "₹1709",
      discount: "39.3% off",
      firstorder: "₹22 discount on 1st order",
      rating: "1039 Reviews",
      rating2: 3.1
    },
    {
      image: "https://images.meesho.com/images/products/44770225/vydao_512.jpg",
      name: "Latest Graceful Men Sandals",
      mkt: "Sold By: Rudu fashion",
      price: "₹1002",
      aprice: "₹1786",
      discount: "43.9% off",
      firstorder: "₹54 discount on 1st order",
      rating: "1033 Reviews",
      rating2: 2.7
    },
    {
      image: "https://images.meesho.com/images/products/66754612/v9fur_512.jpg",
      name: "New Kids Fashions",
      mkt: "Sold By: aditi_fashion",
      price: "₹1159",
      aprice: "₹1773",
      discount: "34.6% off",
      firstorder: "₹9 discount on 1st order",
      rating: "1080 Reviews",
      rating2: 4
    },
    {
      image: "https://images.meesho.com/images/products/80262251/bnykm_512.jpg",
      name: "Trendy Poly Cotton",
      mkt: "Sold By: Civilian Costume",
      price: "₹621",
      aprice: "₹1750",
      discount: "64.5% off",
      firstorder: "₹145 discount on 1st order",
      rating: "1342 Reviews",
      rating2: 3.2
    },
    {
      image: "https://images.meesho.com/images/products/64215169/siwls_512.jpg",
      name: "Beauty & Health Products",
      mkt: "Sold By: SHUBHARAMBH VENTURES",
      price: "₹1217",
      aprice: "₹1713",
      discount: "29.0% off",
      firstorder: "₹72 discount on 1st order",
      rating: "1539 Reviews",
      rating2: 3.6
    },
    {
      image: "https://images.meesho.com/images/products/86171173/83hoz_512.jpg",
      name: "Superior Stylish Kajal",
      mkt: "Sold By: Bewitched Boutique",
      price: "₹525",
      aprice: "₹1735",
      discount: "69.7% off",
      firstorder: "₹14 discount on 1st order",
      rating: "312 Reviews",
      rating2: 2
    },
    {
      image: "https://images.meesho.com/images/products/97093452/qja4t_512.jpg",
      name: "Sarees Ethnic Dresses",
      mkt: "Sold By: Shivtrader",
      price: "₹1674",
      aprice: "₹1764",
      discount: "5.1% off",
      firstorder: "₹119 discount on 1st order",
      rating: "457 Reviews",
      rating2: 3.8
    },
    {
      image: "https://images.meesho.com/images/products/75362149/5rjrg_512.jpg",
      name: "Unique Attractive Deo",
      mkt: "Sold By: TatteredClothing",
      price: "₹1310",
      aprice: "₹1740",
      discount: "24.7% off",
      firstorder: "₹141 discount on 1st order",
      rating: "280 Reviews",
      rating2: 3.8
    },
    {
      image: "https://images.meesho.com/images/products/15856786/78fbe_512.jpg",
      name: "Beauty & Health Products",
      mkt: "Sold By: BrightClothing",
      price: "₹850",
      aprice: "₹1783",
      discount: "52.3% off",
      firstorder: "₹12 discount on 1st order",
      rating: "391 Reviews",
      rating2: 2
    },
    {
      image: "https://images.meesho.com/images/products/3272785/1_512.jpg",
      name: "Trendy TV / Devices",
      mkt: "Sold By: Enough Apparel",
      price: "₹545",
      aprice: "₹1702",
      discount: "68.0% off",
      firstorder: "₹11 discount on 1st order",
      rating: "686 Reviews",
      rating2: 3.2
    },
    {
      image: "https://images.meesho.com/images/products/97417579/qplox_512.jpg",
      name: "Jivika Pretty Sarees",
      mkt: "Sold By: Aromatic",
      price: "₹865",
      aprice: "₹1771",
      discount: "51.2% off",
      firstorder: "₹9 discount on 1st order",
      rating: "180 Reviews",
      rating2: 4.8
    },
    {
      image: "https://images.meesho.com/images/products/77759279/lickm_512.jpg",
      name: "Unique Trendy Sports Shoes",
      mkt: "Sold By: CRAFTOS HANDICRAFTS",
      price: "₹674",
      aprice: "₹1739",
      discount: "61.2% off",
      firstorder: "₹134 discount on 1st order",
      rating: "573 Reviews",
      rating2: 1.7
    },
    {
      image: "https://images.meesho.com/images/products/60202146/irdyd_512.jpg",
      name: "Electrical Wire",
      mkt: "Sold By: Shivtrader",
      price: "₹1593",
      aprice: "₹1714",
      discount: "7.1% off",
      firstorder: "₹20 discount on 1st order",
      rating: "875 Reviews",
      rating2: 4.8
    },
    {
      image: "https://images.meesho.com/images/products/78066568/vkvzs_512.jpg",
      name: "Colorful Jewellery",
      mkt: "Sold By: Shershaan",
      price: "₹891",
      aprice: "₹1756",
      discount: "49.3% off",
      firstorder: "₹114 discount on 1st order",
      rating: "746 Reviews",
      rating2: 3.5
    },
    {
      image: "https://images.meesho.com/images/products/25992878/4f8e4_512.jpg",
      name: "Premium Nourishing Nail",
      mkt: "Sold By: Zalya",
      price: "₹1231",
      aprice: "₹1696",
      discount: "27.4% off",
      firstorder: "₹87 discount on 1st order",
      rating: "27 Reviews",
      rating2: 3
    },
    {
      image: "https://images.meesho.com/images/products/37966089/zfwrk_512.jpg",
      name: "Charvi Fabulous Kurtis",
      mkt: "Sold By: Indian Chikan Factory",
      price: "₹586",
      aprice: "₹636",
      discount: "7.9% off",
      firstorder: "₹91 discount on 1st order",
      rating: "37 Reviews",
      rating2: 3.3
    },
    {
      image: "https://images.meesho.com/images/products/52707380/tdnds_512.jpg",
      name: "Stylo Earrings",
      mkt: "Sold By: Enough Apparel",
      price: "₹1629",
      aprice: "₹1739",
      discount: "6.3% off",
      firstorder: "₹69 discount on 1st order",
      rating: "871 Reviews",
      rating2: 3.7
    },
    {
      image: "https://images.meesho.com/images/products/62948347/icmbh_512.jpg",
      name: "Alite Bejeweled Rings",
      mkt: "Sold By: The Strange",
      price: "₹1255",
      aprice: "₹1785",
      discount: "29.7% off",
      firstorder: "₹68 discount on 1st order",
      rating: "1481 Reviews",
      rating2: 4.5
    },
    {
      image: "https://images.meesho.com/images/products/84176549/kafoh_512.jpg",
      name: "Latest Things For Kids",
      mkt: "Sold By: Krishna Enterprises",
      price: "₹1561",
      aprice: "₹1741",
      discount: "10.3% off",
      firstorder: "₹103 discount on 1st order",
      rating: "1120 Reviews",
      rating2: 4.6
    },
    {
      image: "https://images.meesho.com/images/products/30839757/fqcds_512.jpg",
      name: "Aishani Petite Salwar Suits & Dress Materials",
      mkt: "Sold By: Aadil Handloom",
      price: "₹431",
      aprice: "₹481",
      discount: "10.4% off",
      firstorder: "₹19 discount on 1st order",
      rating: "12 Reviews",
      rating2: 3.9
    },
    {
      image: "https://images.meesho.com/images/products/80527823/tobhj_512.jpg",
      name: "Attractive Bags % Footwear",
      mkt: "Sold By: V King Kohli",
      price: "₹1254",
      aprice: "₹1701",
      discount: "26.3% off",
      firstorder: "₹86 discount on 1st order",
      rating: "212 Reviews",
      rating2: 2
    },
    {
      image: "https://images.meesho.com/images/products/76854886/sru74_512.jpg",
      name: "Morden Beautiful Causals",
      mkt: "Sold By: The Soft Apparel",
      price: "₹1516",
      aprice: "₹1711",
      discount: "11.4% off",
      firstorder: "₹120 discount on 1st order",
      rating: "531 Reviews",
      rating2: 4
    },
    {
      image: "https://images.meesho.com/images/products/68950117/necd9_512.jpg",
      name: "Graceful Nail Paint",
      mkt: "Sold By: The Haphazard Mode",
      price: "₹942",
      aprice: "₹1743",
      discount: "46.0% off",
      firstorder: "₹121 discount on 1st order",
      rating: "175 Reviews",
      rating2: 4.6
    },
    {
      image: "https://images.meesho.com/images/products/37346172/muima_512.jpg",
      name: "Baby Sleeping Bags",
      mkt: "Sold By: Clean Clothe",
      price: "₹1048",
      aprice: "₹1769",
      discount: "40.8% off",
      firstorder: "₹2 discount on 1st order",
      rating: "787 Reviews",
      rating2: 3.2
    },
    {
      image: "https://images.meesho.com/images/products/51805250/hlrhg_512.jpg",
      name: "Sassy Men Vest",
      mkt: "Sold By: The Coarse",
      price: "₹1574",
      aprice: "₹1752",
      discount: "10.2% off",
      firstorder: "₹21 discount on 1st order",
      rating: "647 Reviews",
      rating2: 2.6
   }
   ]